image: php:7.2-fpm-stretch

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -qy unzip git curl libmcrypt-dev
          - yes | pecl install mcrypt-1.0.1
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer config -g github-oauth.github.com $GITHUB_OATH
          - composer install --ignore-platform-reqs
          - ln -f -s .env.pipelines .env
          - php artisan key:generate
          - ./vendor/bin/phpunit