<?php

namespace App\Containers\Checklist\Providers;

use App\Containers\Checklist\Models\Checklist;
use App\Containers\Checklist\Observers\ChecklistObserver;
use App\Ship\Parents\Providers\MainProvider;

/**
 * Class MainServiceProvider.
 *
 * The Main Service Provider of this container, it will be automatically registered in the framework.
 */
class MainServiceProvider extends MainProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Checklist::observe(ChecklistObserver::class);
    }

    /**
     * Container Service Providers.
     *
     * @var array
     */
    public $serviceProviders = [
        // InternalServiceProviderExample::class,
    ];

    /**
     * Container Aliases
     *
     * @var  array
     */
    public $aliases = [
        // 'Foo' => Bar::class,
        'NestedSet' => Kalnoy\NestedSet\NestedSet::class
    ];

    /**
     * Register anything in the container.
     */
    public function register()
    {
        parent::register();

        // $this->app->bind(UserRepositoryInterface::class, UserRepository::class);
        // ...
    }
}
