<?php

namespace App\Containers\Subscription\Data\Repositories;

use App\Ship\Parents\Repositories\Repository;

/**
 * Class SubscriptionRegisterRepository
 */
class SubscriptionRegisterRepository extends Repository
{

    /**
     * @var array
     */
    protected $fieldSearchable = [
        'id' => '=',
        // ...
    ];

    function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
