<?php

namespace App\Containers\Checkpoint\Providers;

use App\Containers\Checkpoint\Models\Checkpoint;
use App\Containers\Checkpoint\Observers\CheckpointObserver;
use App\Ship\Parents\Providers\MainProvider;

/**
 * Class MainServiceProvider.
 *
 * The Main Service Provider of this container, it will be automatically registered in the framework.
 */
class MainServiceProvider extends MainProvider
{


    /**
     * Container Service Providers.
     *
     * @var array
     */
    public $serviceProviders = [
        // InternalServiceProviderExample::class,
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Checkpoint::observe(CheckpointObserver::class);
    }

    /**
     * Container Aliases
     *
     * @var  array
     */
    public $aliases = [
        // 'Foo' => Bar::class,
    ];

    /**
     * Register anything in the container.
     */
    public function register()
    {
        parent::register();

        // $this->app->bind(UserRepositoryInterface::class, UserRepository::class);
        // ...
    }
}
